### ISSUE TITLE
Unxpected token encapsulated (uniontype)

### ISSUE THREAD

**Issue by ptaeuber** [lochel/NppModelica#5]
Outline does not work for encapsulated uniontype (instead of encapsulated package)

**Comment by lochel** [comment]
@ptaeuber I made a pre-release (v1.0.6-beta.1) that has support for encapsulated uniontypes. You can download and test it if you want.
_(Please note, the "update NppModelica" feature does only consider regular releases, which means that you have to download and install this one manually.)_
