### ISSUE TITLE
Problem with indexing

### ISSUE THREAD

**Issue by ptaeuber** [lochel/NppModelica#9]
FFrontend.FCore.mo produces:

Scope: Error in package: Package: Error in package: Der Index lag außerhalb des Bereichs. Er muss nicht negativ und kleiner als die Auflistung sein.
Parametername: indexScope: Error in package: Package: Error in package: Der Index lag außerhalb des Bereichs. Er muss nicht negativ und kleiner als die Auflistung sein.
Parametername: index

**Comment by ptaeuber** [comment]
Same for DAE.mo

**Comment by lochel** [comment]
Fixed with 77538374c65086cd0d315f0cb6796a143c54c5a9.
